CREATE TABLE Board
(
	id INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL,
    body VARCHAR(2047) NOT NULL,
	memberId VARCHAR(255) NOT NULL,
    inserted TIMESTAMP DEFAULT NOW()
);

DROP TABLE Board;


ALTER TABLE Board
MODIFY COLUMN id INT PRIMARY KEY AUTO_INCREMENT;

DESC Board;
USE Practice;

SELECT * FROM Member;
SELECT * FROM Board;

USE Practice;
ALTER TABLE Board 
ADD FOREIGN KEY (MemberId) 
REFERENCES Member(id); 